# -*- coding: utf-8 -*-
"""Copy of REVIEW2MINIPROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cx6gt_4IdmtkiLDYK5ghYzKvdIkOxn9B
"""

# 1. Project Setup & Dataset

from google.colab import drive
drive.mount('/content/drive')

import os

os.listdir('/content/drive/MyDrive/UPI_Fraud_Project')

import pandas as pd

file_path = '/content/drive/MyDrive/UPI_Fraud_Project/indian_banking_transactions.csv'

df = pd.read_csv(file_path)

print(df.shape)

df.head()

# dataset inspection

# Load the original dataset
df = pd.read_csv('/content/drive/MyDrive/UPI_Fraud_Project/indian_banking_transactions.csv')

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print(df['is_fraud'].value_counts())
print(df['is_fraud'].value_counts(normalize=True) * 100)

# 2. Feature Engineering

df['transaction_date'] = pd.to_datetime(df['transaction_date'])

df['transaction_year'] = df['transaction_date'].dt.year
df['transaction_month'] = df['transaction_date'].dt.month
df['transaction_day'] = df['transaction_date'].dt.day
df['transaction_dayofweek'] = df['transaction_date'].dt.dayofweek

print(df[['transaction_date',
          'transaction_year',
          'transaction_month',
          'transaction_day',
          'transaction_dayofweek']].head())

print(df[['transaction_date',
          'transaction_year',
          'transaction_month',
          'transaction_day',
          'transaction_dayofweek']].iloc[[0, 100, 1000, 10000, 100000]])

# Transaction features

df['amount_balance_ratio'] = (
    df['transaction_amount'] / (df['account_balance'] + 1)
)

print(df[['transaction_amount',
          'account_balance',
          'amount_balance_ratio']].head())

df['balance_after_transaction'] = (
    df['account_balance'] - df['transaction_amount']
)

print(df[['account_balance',
          'transaction_amount',
          'balance_after_transaction']].head())

high_value_threshold = df['transaction_amount'].quantile(0.95)

df['high_value_transaction'] = (
    df['transaction_amount'] > high_value_threshold
).astype(int)

print("High-value threshold:", high_value_threshold)
print(df['high_value_transaction'].value_counts())

df['night_transaction'] = (
    (df['transaction_hour'] >= 22) |
    (df['transaction_hour'] <= 5)
).astype(int)

print(df['night_transaction'].value_counts())

df['weekend_transaction'] = (
    df['transaction_dayofweek'] >= 5
).astype(int)

print(df['weekend_transaction'].value_counts())

print("Total columns:", len(df.columns))
print(df.columns.tolist())

# Transaction features updated

transaction_features = [
    'transaction_year',
    'transaction_month',
    'transaction_day',
    'transaction_dayofweek',
    'amount_balance_ratio',
    'balance_after_transaction',
    'high_value_transaction',
    'night_transaction',
    'weekend_transaction'
]

print("Transaction features added:")
display(df[transaction_features].head())

# 3. Behavioral feature engineering

# Sort transactions by customer and date/time
df['transaction_datetime'] = pd.to_datetime(
    df['transaction_date'].astype(str) + ' ' + df['transaction_time'].astype(str)
)

df = df.sort_values(['customer_id', 'transaction_datetime']).reset_index(drop=True)

print("Transactions sorted by customer and time.")

# Calculate each customer's previous average transaction amount
df['customer_avg_amount'] = (
    df.groupby('customer_id')['transaction_amount']
      .transform(lambda x: x.shift().expanding().mean())
)

# For the customer's first transaction, no previous history exists
df['customer_avg_amount'] = df['customer_avg_amount'].fillna(
    df['transaction_amount']
)

print("Behavioral feature created: customer_avg_amount")
print(df[['customer_id', 'transaction_amount', 'customer_avg_amount']].head(10))

# Calculate how much the current transaction differs from the customer's normal amount
df['amount_deviation'] = (
    df['transaction_amount'] / (df['customer_avg_amount'] + 1)
)

print("Behavioral feature created: amount_deviation")
print(df[['customer_id',
          'transaction_amount',
          'customer_avg_amount',
          'amount_deviation']].head(10))

# Count previous transactions made by each customer
df['customer_transaction_count'] = (
    df.groupby('customer_id').cumcount()
)

print("Behavioral feature created: customer_transaction_count")
print(df[['customer_id',
          'transaction_amount',
          'customer_transaction_count']].head(10))

# verify all 3 together

behavioral_features = [
    'customer_avg_amount',
    'amount_deviation',
    'customer_transaction_count'
]

print("Behavioral features created:")
print(behavioral_features)

print("\nSample:")
print(df[
    ['customer_id',
     'transaction_amount',
     'customer_avg_amount',
     'amount_deviation',
     'customer_transaction_count']
].head(10))

# compare behavioral features

print("Behavioral feature comparison:\n")

print("Customer average amount:")
print(df.groupby('is_fraud')['customer_avg_amount'].mean())

print("\nAmount deviation:")
print(df.groupby('is_fraud')['amount_deviation'].mean())

print("\nPrevious transaction count:")
print(df.groupby('is_fraud')['customer_transaction_count'].mean())

# 4. Define X and y

X = df.drop(columns=['is_fraud', 'transaction_datetime'])
y = df['is_fraud']

print("X shape:", X.shape)
print("y shape:", y.shape)

# 5. Train-Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# 6. Preprocessing

categorical_features = [
    'account_type',
    'transaction_type',
    'transaction_direction',
    'merchant_category',
    'state',
    'loan_type',
    'transaction_status',
    'channel',
    'kyc_status'
]

numeric_features = [
    'transaction_amount',
    'account_balance',
    'credit_score',
    'has_loan',
    'emi_amount',
    'transaction_hour',
    'transaction_year',
    'transaction_month',
    'transaction_day',
    'transaction_dayofweek',
    'amount_balance_ratio',
    'balance_after_transaction',
    'high_value_transaction',
    'night_transaction',
    'weekend_transaction',
    'customer_avg_amount',
    'amount_deviation',
    'customer_transaction_count'
]

print("Categorical features:", len(categorical_features))
print("Numerical features:", len(numeric_features))

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

print("Preprocessor updated.")
print("Numerical features:", len(numeric_features))
print("Categorical features:", len(categorical_features))

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Processed X_train shape:", X_train_processed.shape)
print("Processed X_test shape:", X_test_processed.shape)

# 7. Model Training
# 7.1 Logistic Regression

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    class_weight='balanced',
    max_iter=1000,
    random_state=42
)

lr_model.fit(X_train_processed, y_train)

print("Logistic Regression model trained successfully.")

# Make Logistic Regression predictions

y_pred_lr = lr_model.predict(X_test_processed)

print("Predictions generated successfully.")

# Now calculate the Logistic Regression metrics.

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("F1 Score:", f1_score(y_test, y_pred_lr))

y_prob_lr = lr_model.predict_proba(X_test_processed)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_prob_lr))
print("PR-AUC:", average_precision_score(y_test, y_prob_lr))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

# 7.2 Random Forest

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=30,
    max_depth=10,
    class_weight='balanced',
    n_jobs=-1,
    random_state=42
)

rf_model.fit(X_train_processed, y_train)

print("Random Forest model trained successfully.")

# Make Random Forest predictions

y_pred_rf = rf_model.predict(X_test_processed)

print("Random Forest predictions generated successfully.")

# Now calculate the Random Forest metrics.

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))

y_prob_rf = rf_model.predict_proba(X_test_processed)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_prob_rf))
print("PR-AUC:", average_precision_score(y_test, y_prob_rf))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

# 7.3 XGBoost

from xgboost import XGBClassifier

fraud_count = y_train.sum()
genuine_count = (y_train == 0).sum()

scale_pos_weight = genuine_count / fraud_count

print("scale_pos_weight:", scale_pos_weight)

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train_processed, y_train)

print("XGBoost model trained successfully.")

# Make XGBoost predictions

y_pred_xgb = xgb_model.predict(X_test_processed)

print("XGBoost predictions generated successfully.")

# Now calculate the XGBoost metrics.

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall:", recall_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb))

y_prob_xgb = xgb_model.predict_proba(X_test_processed)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_prob_xgb))
print("PR-AUC:", average_precision_score(y_test, y_prob_xgb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

# 8. Model Evaluation & Comparison

comparison = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Random Forest',
        'XGBoost'
    ],
    'Accuracy': [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_xgb)
    ],
    'Precision': [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_rf),
        precision_score(y_test, y_pred_xgb)
    ],
    'Recall': [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_rf),
        recall_score(y_test, y_pred_xgb)
    ],
    'F1 Score': [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_xgb)
    ],
    'ROC-AUC': [
        roc_auc_score(y_test, y_prob_lr),
        roc_auc_score(y_test, y_prob_rf),
        roc_auc_score(y_test, y_prob_xgb)
    ],
    'PR-AUC': [
        average_precision_score(y_test, y_prob_lr),
        average_precision_score(y_test, y_prob_rf),
        average_precision_score(y_test, y_prob_xgb)
    ]
})

print(comparison.round(4))

comparison_percent = comparison.copy()

for col in ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC-AUC', 'PR-AUC']:
    comparison_percent[col] = (
        comparison_percent[col] * 100
    ).round(2)

print(comparison_percent.to_string(index=False))

# Transaction amount summary

amount_summary = df.groupby('is_fraud')['transaction_amount'].agg(
    ['mean', 'median', 'max']
)

print(amount_summary)

# Transaction type

type_analysis = df.groupby('transaction_type')['is_fraud'].agg(
    ['count', 'sum', 'mean']
)

type_analysis['fraud_rate_percent'] = type_analysis['mean'] * 100

print(
    type_analysis
    .sort_values('fraud_rate_percent', ascending=False)
    .round(4)
)

# High-value transactions

high_value_analysis = df.groupby('high_value_transaction')['is_fraud'].agg(
    ['count', 'sum', 'mean']
)

high_value_analysis['fraud_rate_percent'] = (
    high_value_analysis['mean'] * 100
)

print(high_value_analysis.round(4))

# balance ratio

ratio_analysis = df.groupby('is_fraud')['amount_balance_ratio'].agg(
    ['mean', 'median', 'max']
)

print(ratio_analysis)

# 9. Feature importance

feature_names = preprocessor.get_feature_names_out()

importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': rf_model.feature_importances_
}).sort_values('importance', ascending=False)

print(importance_df.head(15))

# 10. Behavioral Feature Analysis

print("Behavioral Feature Analysis\n")

print("1. Amount Deviation:")
print(df.groupby('is_fraud')['amount_deviation'].mean())

print("\n2. Customer Average Amount:")
print(df.groupby('is_fraud')['customer_avg_amount'].mean())

print("\n3. Customer Transaction Count:")
print(df.groupby('is_fraud')['customer_transaction_count'].mean())

# 11. Fraud Score Mechanism

# Generate fraud probability scores using Random Forest

fraud_score = rf_model.predict_proba(X_test_processed)[:, 1]

print("Sample fraud scores:")
print(fraud_score[:10])

# Convert fraud score into binary fraud prediction

threshold = 0.5

fraud_prediction = (fraud_score >= threshold).astype(int)

print("Threshold:", threshold)
print("Sample fraud scores:", fraud_score[:10])
print("Sample fraud predictions:", fraud_prediction[:10])

# Show transactions with the highest fraud scores

top_scores = pd.DataFrame({
    'Fraud Score': fraud_score,
    'Prediction': fraud_prediction
}).sort_values('Fraud Score', ascending=False)

print(top_scores.head(10))

